# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainwnd.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(616, 273)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/badge.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_ip = QtWidgets.QLabel(MainWindow)
        self.label_ip.setFrameShape(QtWidgets.QFrame.Box)
        self.label_ip.setObjectName("label_ip")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_ip)
        self.label_status = QtWidgets.QLabel(MainWindow)
        self.label_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_status.setObjectName("label_status")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_status)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_refresh = QtWidgets.QPushButton(MainWindow)
        self.btn_refresh.setObjectName("btn_refresh")
        self.horizontalLayout.addWidget(self.btn_refresh)
        self.btn_start = QtWidgets.QPushButton(MainWindow)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout.addWidget(self.btn_start)
        self.btn_stop = QtWidgets.QPushButton(MainWindow)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout.addWidget(self.btn_stop)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_install = QtWidgets.QPushButton(MainWindow)
        self.btn_install.setObjectName("btn_install")
        self.horizontalLayout_2.addWidget(self.btn_install)
        self.btn_uninstall = QtWidgets.QPushButton(MainWindow)
        self.btn_uninstall.setObjectName("btn_uninstall")
        self.horizontalLayout_2.addWidget(self.btn_uninstall)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RegBook Server"))
        self.label_ip.setText(_translate("MainWindow", "<span style=\"font-size:32pt;font-weight: bold;color:black;\">IP&nbsp;&nbsp;:</span><span style=\"font-size:32pt;font-weight: bold;color:green;\">localhost</span>"))
        self.label_status.setText(_translate("MainWindow", "<span style=\"font-size:32pt;font-weight: bold;color:black;\">STATUS:</span><span style=\"font-size:32pt;font-weight: bold;color:grey;\">Not Exist</span>"))
        self.btn_refresh.setText(_translate("MainWindow", "Refresh"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_stop.setText(_translate("MainWindow", "Stop"))
        self.btn_install.setText(_translate("MainWindow", "Install"))
        self.btn_uninstall.setText(_translate("MainWindow", "Uninstall"))
import resouce_rc
