# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\MediaManageDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MediaManagDlg(object):
    def setupUi(self, MediaManagDlg):
        MediaManagDlg.setObjectName("MediaManagDlg")
        MediaManagDlg.resize(742, 578)
        self.buttonBox = QtWidgets.QDialogButtonBox(MediaManagDlg)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(MediaManagDlg)
        self.buttonBox.accepted.connect(MediaManagDlg.accept)
        self.buttonBox.rejected.connect(MediaManagDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(MediaManagDlg)

    def retranslateUi(self, MediaManagDlg):
        _translate = QtCore.QCoreApplication.translate
        MediaManagDlg.setWindowTitle(_translate("MediaManagDlg", "Media Manage"))
