# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\MediaManageDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MediaManagDlg(object):
    def setupUi(self, MediaManagDlg):
        MediaManagDlg.setObjectName("MediaManagDlg")
        MediaManagDlg.resize(640, 480)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MediaManagDlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(MediaManagDlg)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listView = QtWidgets.QListView(self.groupBox)
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.listView.setViewMode(QtWidgets.QListView.IconMode)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.uploadButton = QtWidgets.QPushButton(MediaManagDlg)
        self.uploadButton.setObjectName("uploadButton")
        self.horizontalLayout.addWidget(self.uploadButton)
        self.downloadButton = QtWidgets.QPushButton(MediaManagDlg)
        self.downloadButton.setObjectName("downloadButton")
        self.horizontalLayout.addWidget(self.downloadButton)
        self.previewButton = QtWidgets.QPushButton(MediaManagDlg)
        self.previewButton.setObjectName("previewButton")
        self.horizontalLayout.addWidget(self.previewButton)
        self.exitButton = QtWidgets.QPushButton(MediaManagDlg)
        self.exitButton.setDefault(True)
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout.addWidget(self.exitButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(MediaManagDlg)
        self.exitButton.clicked.connect(MediaManagDlg.accept)
        QtCore.QMetaObject.connectSlotsByName(MediaManagDlg)

    def retranslateUi(self, MediaManagDlg):
        _translate = QtCore.QCoreApplication.translate
        MediaManagDlg.setWindowTitle(_translate("MediaManagDlg", "Media Manage"))
        self.groupBox.setTitle(_translate("MediaManagDlg", "Owner Name"))
        self.uploadButton.setText(_translate("MediaManagDlg", "Upload(&U)"))
        self.downloadButton.setText(_translate("MediaManagDlg", "Download(&D)"))
        self.previewButton.setText(_translate("MediaManagDlg", "Preview(&P)"))
        self.exitButton.setText(_translate("MediaManagDlg", "Exit(&X)"))
