# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\MediaManageDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MediaManagDlg(object):
    def setupUi(self, MediaManagDlg):
        MediaManagDlg.setObjectName("MediaManagDlg")
        MediaManagDlg.resize(1250, 600)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(MediaManagDlg)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(MediaManagDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.ownerGbox = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ownerGbox.sizePolicy().hasHeightForWidth())
        self.ownerGbox.setSizePolicy(sizePolicy)
        self.ownerGbox.setObjectName("ownerGbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ownerGbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listView = QtWidgets.QListView(self.ownerGbox)
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listView.setResizeMode(QtWidgets.QListView.Adjust)
        self.listView.setGridSize(QtCore.QSize(200, 200))
        self.listView.setViewMode(QtWidgets.QListView.IconMode)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.exifGbox = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exifGbox.sizePolicy().hasHeightForWidth())
        self.exifGbox.setSizePolicy(sizePolicy)
        self.exifGbox.setObjectName("exifGbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.exifGbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.exifText = QtWidgets.QTextEdit(self.exifGbox)
        self.exifText.setReadOnly(True)
        self.exifText.setObjectName("exifText")
        self.verticalLayout_2.addWidget(self.exifText)
        self.verticalLayout_3.addWidget(self.splitter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.uploadButton = QtWidgets.QPushButton(MediaManagDlg)
        self.uploadButton.setObjectName("uploadButton")
        self.horizontalLayout.addWidget(self.uploadButton)
        self.downloadButton = QtWidgets.QPushButton(MediaManagDlg)
        self.downloadButton.setObjectName("downloadButton")
        self.horizontalLayout.addWidget(self.downloadButton)
        self.previewButton = QtWidgets.QPushButton(MediaManagDlg)
        self.previewButton.setObjectName("previewButton")
        self.horizontalLayout.addWidget(self.previewButton)
        self.deleteButton = QtWidgets.QPushButton(MediaManagDlg)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)
        self.exitButton = QtWidgets.QPushButton(MediaManagDlg)
        self.exitButton.setDefault(True)
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout.addWidget(self.exitButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(MediaManagDlg)
        self.exitButton.clicked.connect(MediaManagDlg.accept)
        QtCore.QMetaObject.connectSlotsByName(MediaManagDlg)

    def retranslateUi(self, MediaManagDlg):
        _translate = QtCore.QCoreApplication.translate
        MediaManagDlg.setWindowTitle(_translate("MediaManagDlg", "Media Manage"))
        self.ownerGbox.setTitle(_translate("MediaManagDlg", "Owner Name"))
        self.exifGbox.setTitle(_translate("MediaManagDlg", "Exif Information"))
        self.uploadButton.setText(_translate("MediaManagDlg", "Upload(&U)"))
        self.downloadButton.setText(_translate("MediaManagDlg", "Download(&D)"))
        self.previewButton.setText(_translate("MediaManagDlg", "Preview(&P)"))
        self.deleteButton.setText(_translate("MediaManagDlg", "Delete(&E)"))
        self.exitButton.setText(_translate("MediaManagDlg", "Exit(&X)"))
