# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\MemberManageView.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MemberManageView(object):
    def setupUi(self, MemberManageView):
        MemberManageView.setObjectName("MemberManageView")
        MemberManageView.resize(967, 457)
        self.verticalLayout = QtWidgets.QVBoxLayout(MemberManageView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.keywordLabel = QtWidgets.QLabel(MemberManageView)
        self.keywordLabel.setObjectName("keywordLabel")
        self.horizontalLayout_2.addWidget(self.keywordLabel)
        self.keywordEdit = QtWidgets.QLineEdit(MemberManageView)
        self.keywordEdit.setObjectName("keywordEdit")
        self.horizontalLayout_2.addWidget(self.keywordEdit)
        self.findButton = QtWidgets.QPushButton(MemberManageView)
        self.findButton.setObjectName("findButton")
        self.horizontalLayout_2.addWidget(self.findButton)
        self.refreshButton = QtWidgets.QPushButton(MemberManageView)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_2.addWidget(self.refreshButton)
        self.line = QtWidgets.QFrame(MemberManageView)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        spacerItem = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.addButton = QtWidgets.QPushButton(MemberManageView)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_2.addWidget(self.addButton)
        self.delButton = QtWidgets.QPushButton(MemberManageView)
        self.delButton.setObjectName("delButton")
        self.horizontalLayout_2.addWidget(self.delButton)
        self.modifyButton = QtWidgets.QPushButton(MemberManageView)
        self.modifyButton.setObjectName("modifyButton")
        self.horizontalLayout_2.addWidget(self.modifyButton)
        self.printButton = QtWidgets.QPushButton(MemberManageView)
        self.printButton.setObjectName("printButton")
        self.horizontalLayout_2.addWidget(self.printButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.baseView = QtWidgets.QTableView(MemberManageView)
        self.baseView.setAlternatingRowColors(True)
        self.baseView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.baseView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.baseView.setObjectName("baseView")
        self.verticalLayout.addWidget(self.baseView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.totalpageLabel = QtWidgets.QLabel(MemberManageView)
        self.totalpageLabel.setObjectName("totalpageLabel")
        self.horizontalLayout.addWidget(self.totalpageLabel)
        self.prepageButton = QtWidgets.QPushButton(MemberManageView)
        self.prepageButton.setObjectName("prepageButton")
        self.horizontalLayout.addWidget(self.prepageButton)
        self.nextpageButton = QtWidgets.QPushButton(MemberManageView)
        self.nextpageButton.setObjectName("nextpageButton")
        self.horizontalLayout.addWidget(self.nextpageButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.keywordLabel.setBuddy(self.keywordEdit)

        self.retranslateUi(MemberManageView)
        QtCore.QMetaObject.connectSlotsByName(MemberManageView)

    def retranslateUi(self, MemberManageView):
        _translate = QtCore.QCoreApplication.translate
        MemberManageView.setWindowTitle(_translate("MemberManageView", "录入结算"))
        self.keywordLabel.setText(_translate("MemberManageView", "关键字(&K)"))
        self.keywordEdit.setPlaceholderText(_translate("MemberManageView", "姓名,身份证,电话,产权/土地证明"))
        self.findButton.setText(_translate("MemberManageView", "查找(&F)"))
        self.refreshButton.setText(_translate("MemberManageView", "重置(&R)"))
        self.addButton.setText(_translate("MemberManageView", "添加(&A)"))
        self.delButton.setText(_translate("MemberManageView", "删除(&D)"))
        self.modifyButton.setText(_translate("MemberManageView", "修改(&M)"))
        self.printButton.setText(_translate("MemberManageView", "打印(&P)"))
        self.totalpageLabel.setText(_translate("MemberManageView", "共 xxx页"))
        self.prepageButton.setText(_translate("MemberManageView", "上一页(&P)"))
        self.nextpageButton.setText(_translate("MemberManageView", "下一页(&N)"))
