# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\ProgressDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProgressDlg(object):
    def setupUi(self, ProgressDlg):
        ProgressDlg.setObjectName("ProgressDlg")
        ProgressDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        ProgressDlg.resize(300, 80)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProgressDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressTxt = QtWidgets.QLabel(ProgressDlg)
        self.progressTxt.setObjectName("progressTxt")
        self.verticalLayout.addWidget(self.progressTxt)
        self.progressBar = QtWidgets.QProgressBar(ProgressDlg)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)

        self.retranslateUi(ProgressDlg)
        QtCore.QMetaObject.connectSlotsByName(ProgressDlg)

    def retranslateUi(self, ProgressDlg):
        _translate = QtCore.QCoreApplication.translate
        ProgressDlg.setWindowTitle(_translate("ProgressDlg", "Please Waiting ..."))
        self.progressTxt.setText(_translate("ProgressDlg", "Processing..."))
