# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\PhotoEditorDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PhotoEditorDlg(object):
    def setupUi(self, PhotoEditorDlg, photowidget):
        PhotoEditorDlg.setObjectName("PhotoEditorDlg")
        PhotoEditorDlg.resize(640, 480)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(PhotoEditorDlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.photoWidget = photowidget
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.photoWidget.sizePolicy().hasHeightForWidth())
        self.photoWidget.setSizePolicy(sizePolicy)
        self.photoWidget.setObjectName("photoWidget")
        self.verticalLayout_2.addWidget(self.photoWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(PhotoEditorDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(32, 32))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/zoomout.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.zoomSlider = QtWidgets.QSlider(PhotoEditorDlg)
        self.zoomSlider.setMinimum(10)
        self.zoomSlider.setMaximum(50)
        self.zoomSlider.setPageStep(5)
        self.zoomSlider.setProperty("value", 10)
        self.zoomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.zoomSlider.setObjectName("zoomSlider")
        self.horizontalLayout.addWidget(self.zoomSlider)
        self.label_2 = QtWidgets.QLabel(PhotoEditorDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(32, 32))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/zoomin.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.rorateLeft = QtWidgets.QPushButton(PhotoEditorDlg)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/roratel.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rorateLeft.setIcon(icon)
        self.rorateLeft.setIconSize(QtCore.QSize(32, 32))
        self.rorateLeft.setObjectName("rorateLeft")
        self.horizontalLayout_2.addWidget(self.rorateLeft)
        self.rorateRight = QtWidgets.QPushButton(PhotoEditorDlg)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/rorater.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rorateRight.setIcon(icon1)
        self.rorateRight.setIconSize(QtCore.QSize(32, 32))
        self.rorateRight.setObjectName("rorateRight")
        self.horizontalLayout_2.addWidget(self.rorateRight)
        self.buttonBox = QtWidgets.QDialogButtonBox(PhotoEditorDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(PhotoEditorDlg)
        self.buttonBox.accepted.connect(PhotoEditorDlg.accept)
        self.buttonBox.rejected.connect(PhotoEditorDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(PhotoEditorDlg)

    def retranslateUi(self, PhotoEditorDlg):
        _translate = QtCore.QCoreApplication.translate
        PhotoEditorDlg.setWindowTitle(_translate("PhotoEditorDlg", "Photo Editor"))


import resouce_rc
