# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\ResetPwdDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RestPwdDlg(object):
    def setupUi(self, RestPwdDlg):
        RestPwdDlg.setObjectName("RestPwdDlg")
        RestPwdDlg.resize(400, 220)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/app.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RestPwdDlg.setWindowIcon(icon)
        RestPwdDlg.setSizeGripEnabled(False)
        RestPwdDlg.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(RestPwdDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titlelabel = QtWidgets.QLabel(RestPwdDlg)
        self.titlelabel.setObjectName("titlelabel")
        self.verticalLayout.addWidget(self.titlelabel)
        self.line = QtWidgets.QFrame(RestPwdDlg)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.usernamelabel = QtWidgets.QLabel(RestPwdDlg)
        self.usernamelabel.setObjectName("usernamelabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernamelabel)
        self.username = QtWidgets.QLineEdit(RestPwdDlg)
        self.username.setEnabled(False)
        self.username.setObjectName("username")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.username)
        self.pwdlabel = QtWidgets.QLabel(RestPwdDlg)
        self.pwdlabel.setObjectName("pwdlabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pwdlabel)
        self.newpwd = QtWidgets.QLineEdit(RestPwdDlg)
        self.newpwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newpwd.setObjectName("newpwd")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.newpwd)
        self.repeatlabel = QtWidgets.QLabel(RestPwdDlg)
        self.repeatlabel.setObjectName("repeatlabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.repeatlabel)
        self.confirmpwd = QtWidgets.QLineEdit(RestPwdDlg)
        self.confirmpwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmpwd.setObjectName("confirmpwd")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.confirmpwd)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(131, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.okButton = QtWidgets.QPushButton(RestPwdDlg)
        self.okButton.setEnabled(False)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_3.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(RestPwdDlg)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_3.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.usernamelabel.setBuddy(self.username)
        self.pwdlabel.setBuddy(self.newpwd)
        self.repeatlabel.setBuddy(self.confirmpwd)

        self.retranslateUi(RestPwdDlg)
        self.okButton.clicked.connect(RestPwdDlg.accept)
        self.cancelButton.clicked.connect(RestPwdDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(RestPwdDlg)

    def retranslateUi(self, RestPwdDlg):
        _translate = QtCore.QCoreApplication.translate
        RestPwdDlg.setWindowTitle(_translate("RestPwdDlg", "User Manage"))
        self.titlelabel.setText(_translate("RestPwdDlg", "Reset Password"))
        self.usernamelabel.setText(_translate("RestPwdDlg", "User Name(&U)  "))
        self.pwdlabel.setText(_translate("RestPwdDlg", "New Password(&N)  "))
        self.repeatlabel.setText(_translate("RestPwdDlg", "Confirm Password(&R)"))
        self.okButton.setText(_translate("RestPwdDlg", "Ok(&O)"))
        self.cancelButton.setText(_translate("RestPwdDlg", "Cancel(&C)"))
import resouce_rc
