# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\RegisterDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterDlg(object):
    def setupUi(self, RegisterDlg):
        RegisterDlg.setObjectName("RegisterDlg")
        RegisterDlg.resize(400, 250)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/app.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RegisterDlg.setWindowIcon(icon)
        RegisterDlg.setSizeGripEnabled(False)
        RegisterDlg.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(RegisterDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titlelabel = QtWidgets.QLabel(RegisterDlg)
        self.titlelabel.setObjectName("titlelabel")
        self.verticalLayout.addWidget(self.titlelabel)
        self.line = QtWidgets.QFrame(RegisterDlg)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.usernamelabel = QtWidgets.QLabel(RegisterDlg)
        self.usernamelabel.setObjectName("usernamelabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernamelabel)
        self.username = QtWidgets.QLineEdit(RegisterDlg)
        self.username.setObjectName("username")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.username)
        self.isadmin = QtWidgets.QCheckBox(RegisterDlg)
        self.isadmin.setObjectName("isadmin")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.isadmin)
        self.pwdlabel = QtWidgets.QLabel(RegisterDlg)
        self.pwdlabel.setObjectName("pwdlabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pwdlabel)
        self.pwd = QtWidgets.QLineEdit(RegisterDlg)
        self.pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd.setObjectName("pwd")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pwd)
        self.repeatlabel = QtWidgets.QLabel(RegisterDlg)
        self.repeatlabel.setObjectName("repeatlabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.repeatlabel)
        self.confirmpwd = QtWidgets.QLineEdit(RegisterDlg)
        self.confirmpwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmpwd.setObjectName("confirmpwd")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.confirmpwd)
        self.usernamelabel_2 = QtWidgets.QLabel(RegisterDlg)
        self.usernamelabel_2.setObjectName("usernamelabel_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.usernamelabel_2)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(131, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.okButton = QtWidgets.QPushButton(RegisterDlg)
        self.okButton.setEnabled(False)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_3.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(RegisterDlg)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_3.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.usernamelabel.setBuddy(self.username)
        self.pwdlabel.setBuddy(self.pwd)
        self.repeatlabel.setBuddy(self.confirmpwd)
        self.usernamelabel_2.setBuddy(self.isadmin)

        self.retranslateUi(RegisterDlg)
        self.okButton.clicked.connect(RegisterDlg.accept)
        self.cancelButton.clicked.connect(RegisterDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(RegisterDlg)
        RegisterDlg.setTabOrder(self.username, self.isadmin)
        RegisterDlg.setTabOrder(self.isadmin, self.pwd)
        RegisterDlg.setTabOrder(self.pwd, self.confirmpwd)
        RegisterDlg.setTabOrder(self.confirmpwd, self.okButton)
        RegisterDlg.setTabOrder(self.okButton, self.cancelButton)

    def retranslateUi(self, RegisterDlg):
        _translate = QtCore.QCoreApplication.translate
        RegisterDlg.setWindowTitle(_translate("RegisterDlg", "User Manage"))
        self.titlelabel.setText(_translate("RegisterDlg", "Register User"))
        self.usernamelabel.setText(_translate("RegisterDlg", "User Name(&U)  "))
        self.isadmin.setText(_translate("RegisterDlg", "Administrator"))
        self.pwdlabel.setText(_translate("RegisterDlg", "New Password(&N)  "))
        self.repeatlabel.setText(_translate("RegisterDlg", "Confirm Password(&R)"))
        self.usernamelabel_2.setText(_translate("RegisterDlg", "Role(&R)"))
        self.okButton.setText(_translate("RegisterDlg", "Ok(&O)"))
        self.cancelButton.setText(_translate("RegisterDlg", "Cancel(&C)"))
import resouce_rc
