# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\TmplDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TmplDlg(object):
    def setupUi(self, TmplDlg):
        TmplDlg.setObjectName("TmplDlg")
        TmplDlg.resize(540, 182)
        self.verticalLayout = QtWidgets.QVBoxLayout(TmplDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(TmplDlg)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.tmplBox = QtWidgets.QComboBox(self.groupBox)
        self.tmplBox.setObjectName("tmplBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tmplBox)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(TmplDlg)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nothingButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.nothingButton.setChecked(True)
        self.nothingButton.setObjectName("nothingButton")
        self.horizontalLayout.addWidget(self.nothingButton)
        self.openButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.openButton.setObjectName("openButton")
        self.horizontalLayout.addWidget(self.openButton)
        self.printButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.printButton.setObjectName("printButton")
        self.horizontalLayout.addWidget(self.printButton)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(TmplDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(TmplDlg)
        self.buttonBox.accepted.connect(TmplDlg.accept)
        self.buttonBox.rejected.connect(TmplDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(TmplDlg)

    def retranslateUi(self, TmplDlg):
        _translate = QtCore.QCoreApplication.translate
        TmplDlg.setWindowTitle(_translate("TmplDlg", "Template"))
        self.groupBox.setTitle(_translate("TmplDlg", "Template"))
        self.label.setText(_translate("TmplDlg", "Please choose the template:"))
        self.groupBox_2.setTitle(_translate("TmplDlg", "Next Action"))
        self.nothingButton.setText(_translate("TmplDlg", "Nonting"))
        self.openButton.setText(_translate("TmplDlg", "Open Document"))
        self.printButton.setText(_translate("TmplDlg", "Print Document"))
