# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\TestDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDlg(object):
    def setupUi(self, LoginDlg):
        LoginDlg.setObjectName("LoginDlg")
        LoginDlg.resize(358, 118)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/app.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginDlg.setWindowIcon(icon)
        LoginDlg.setSizeGripEnabled(False)
        LoginDlg.setModal(True)
        self.pushButton = QtWidgets.QPushButton(LoginDlg)
        self.pushButton.setGeometry(QtCore.QRect(30, 50, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.okButton = QtWidgets.QPushButton(LoginDlg)
        self.okButton.setGeometry(QtCore.QRect(129, 48, 93, 28))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(LoginDlg)
        self.cancelButton.setGeometry(QtCore.QRect(228, 48, 93, 28))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(LoginDlg)
        self.okButton.clicked.connect(LoginDlg.accept)
        self.cancelButton.clicked.connect(LoginDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(LoginDlg)
        LoginDlg.setTabOrder(self.okButton, self.cancelButton)

    def retranslateUi(self, LoginDlg):
        _translate = QtCore.QCoreApplication.translate
        LoginDlg.setWindowTitle(_translate("LoginDlg", "Login"))
        self.pushButton.setText(_translate("LoginDlg", "Test"))
        self.okButton.setText(_translate("LoginDlg", "Login(&O)"))
        self.cancelButton.setText(_translate("LoginDlg", "Quit(&Q)"))
import resouce_rc
