nation:
  - Filipino
  - Chinese
sex:
  - Famale
  - Male
education:
  - Elementary
  - High School
  - College
occupation:
  - Student
  - Businessman
  - Employee
familyrole:
  - Husband
  - Wife
  - Son
  - Daughter
language:
  - Level 1
  - Level 2
  - Level 3
  - Level 4
  - Level 5
meeting:
  - 2017 special meeting
  - 2018 special meeting
  - 2019 special meeting
