# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ChruchProjects\regbook\regbclt\ui\ChangePwdDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangePwdDlg(object):
   def setupUi(self, ChangePwdDlg):
      ChangePwdDlg.setObjectName("ChangePwdDlg")
      ChangePwdDlg.resize(400, 250)
      ChangePwdDlg.setSizeGripEnabled(False)
      ChangePwdDlg.setModal(True)
      self.verticalLayout = QtWidgets.QVBoxLayout(ChangePwdDlg)
      self.verticalLayout.setObjectName("verticalLayout")
      self.titlelabel = QtWidgets.QLabel(ChangePwdDlg)
      self.titlelabel.setObjectName("titlelabel")
      self.verticalLayout.addWidget(self.titlelabel)
      self.line = QtWidgets.QFrame(ChangePwdDlg)
      self.line.setFrameShape(QtWidgets.QFrame.HLine)
      self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
      self.line.setObjectName("line")
      self.verticalLayout.addWidget(self.line)
      self.formLayout = QtWidgets.QFormLayout()
      self.formLayout.setObjectName("formLayout")
      self.userLabel = QtWidgets.QLabel(ChangePwdDlg)
      self.userLabel.setObjectName("userLabel")
      self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.userLabel)
      self.username = QtWidgets.QLineEdit(ChangePwdDlg)
      self.username.setEnabled(False)
      self.username.setObjectName("username")
      self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.username)
      self.oldpwdlabel = QtWidgets.QLabel(ChangePwdDlg)
      self.oldpwdlabel.setObjectName("oldpwdlabel")
      self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.oldpwdlabel)
      self.oldpwd = QtWidgets.QLineEdit(ChangePwdDlg)
      self.oldpwd.setEchoMode(QtWidgets.QLineEdit.Password)
      self.oldpwd.setObjectName("oldpwd")
      self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.oldpwd)
      self.pwdlabel = QtWidgets.QLabel(ChangePwdDlg)
      self.pwdlabel.setObjectName("pwdlabel")
      self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pwdlabel)
      self.newpwd = QtWidgets.QLineEdit(ChangePwdDlg)
      self.newpwd.setEchoMode(QtWidgets.QLineEdit.Password)
      self.newpwd.setObjectName("newpwd")
      self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.newpwd)
      self.repeatlabel = QtWidgets.QLabel(ChangePwdDlg)
      self.repeatlabel.setObjectName("repeatlabel")
      self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.repeatlabel)
      self.confirmpwd = QtWidgets.QLineEdit(ChangePwdDlg)
      self.confirmpwd.setEchoMode(QtWidgets.QLineEdit.Password)
      self.confirmpwd.setObjectName("confirmpwd")
      self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.confirmpwd)
      self.verticalLayout.addLayout(self.formLayout)
      spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
      self.verticalLayout.addItem(spacerItem)
      self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
      self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
      self.horizontalLayout_3.setSpacing(6)
      self.horizontalLayout_3.setObjectName("horizontalLayout_3")
      spacerItem1 = QtWidgets.QSpacerItem(131, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
      self.horizontalLayout_3.addItem(spacerItem1)
      self.okButton = QtWidgets.QPushButton(ChangePwdDlg)
      self.okButton.setEnabled(False)
      self.okButton.setObjectName("okButton")
      self.horizontalLayout_3.addWidget(self.okButton)
      self.cancelButton = QtWidgets.QPushButton(ChangePwdDlg)
      self.cancelButton.setObjectName("cancelButton")
      self.horizontalLayout_3.addWidget(self.cancelButton)
      self.verticalLayout.addLayout(self.horizontalLayout_3)
      self.userLabel.setBuddy(self.username)
      self.oldpwdlabel.setBuddy(self.oldpwd)
      self.pwdlabel.setBuddy(self.newpwd)
      self.repeatlabel.setBuddy(self.confirmpwd)

      self.retranslateUi(ChangePwdDlg)
      self.okButton.clicked.connect(ChangePwdDlg.accept)
      self.cancelButton.clicked.connect(ChangePwdDlg.reject)
      QtCore.QMetaObject.connectSlotsByName(ChangePwdDlg)

   def retranslateUi(self, ChangePwdDlg):
      _translate = QtCore.QCoreApplication.translate
      ChangePwdDlg.setWindowTitle(_translate("ChangePwdDlg", "User Manage"))
      self.titlelabel.setText(_translate("ChangePwdDlg", "Change password"))
      self.userLabel.setText(_translate("ChangePwdDlg", "User Name(&U)  "))
      self.oldpwdlabel.setText(_translate("ChangePwdDlg", "Old Password(&D)  "))
      self.pwdlabel.setText(_translate("ChangePwdDlg", "New Password(&N)  "))
      self.repeatlabel.setText(_translate("ChangePwdDlg", "Confirm Password(&R)"))
      self.okButton.setText(_translate("ChangePwdDlg", "Ok(&O)"))
      self.cancelButton.setText(_translate("ChangePwdDlg", "Cancel(&C)"))
import resouce_rc


if __name__ == "__main__":
   import sys
   app = QtWidgets.QApplication(sys.argv)
   ChangePwdDlg = QtWidgets.QDialog()
   ui = Ui_ChangePwdDlg()
   ui.setupUi(ChangePwdDlg)
   ChangePwdDlg.show()
   sys.exit(app.exec_())
